source("https://rubygems.org")

gem("sinatra")
gem("sinatra-contrib", :require => "sinatra/reloader")
gem("sinatra-activerecord")
gem("rake")
gem("pg")
gem('pry')
gem('capybara')
gem('shoulda-matchers')

group(:test) do
  gem("rspec")
end
